openapi: 3.0.0
info:
  title: Catálogo MERN API - Productos
  version: 1.0.0
  description: Documentación de los endpoints para la gestión de productos en la API del catálogo MERN
servers:
  - url: http://localhost:5000
    description: Servidor local
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JwtCookieToken
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "68eae6824fc877ff9e017d33"
          description: ID del producto (ObjectId de MongoDB)
        name:
          type: string
          example: "Camiseta de Algodón"
          description: Nombre del producto
        description:
          type: string
          example: "Una camiseta cómoda y elegante para cualquier ocasión"
          description: Descripción del producto
        precio:
          type: number
          example: 29.99
          description: Precio del producto
        stock:
          type: number
          example: 50
          description: Cantidad en stock
        imageUrl:
          type: string
          example: "/uploads/1634567890123.jpg"
          description: URL de la imagen del producto
      required:
        - name
        - description
        - precio
        - stock
        - imageUrl
    ProductCreate:
      type: object
      properties:
        name:
          type: string
          example: "Camiseta de Algodón"
        description:
          type: string
          example: "Una camiseta cómoda y elegante"
        precio:
          type: number
          example: 29.99
        stock:
          type: number
          example: 50
        image:
          type: string
          format: binary
          description: Archivo de imagen del producto
      required:
        - name
        - description
        - precio
        - stock
    ProductUpdate:
      type: object
      properties:
        name:
          type: string
          example: "Camiseta de Algodón Actualizada"
        description:
          type: string
          example: "Descripción actualizada"
        precio:
          type: number
          example: 39.99
        stock:
          type: number
          example: 40
        image:
          type: string
          format: binary
          description: Nuevo archivo de imagen (opcional)
paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error al obtener productos"
    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '201':
          description: Producto creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized: Usuario no autenticado"
        '403':
          description: Rol insuficiente
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Forbidden: Rol insuficiente"
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error al crear producto"
  /api/products/{id}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto (ObjectId de MongoDB)
      responses:
        '200':
          description: Detalles del producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Producto no encontrado"
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error al obtener producto"
    put:
      summary: Actualizar un producto por ID
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto (ObjectId de MongoDB)
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Producto actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized: Usuario no autenticado"
        '403':
          description: Rol insuficiente
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Forbidden: Rol insuficiente"
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Producto no encontrado"
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error al actualizar producto"
    delete:
      summary: Eliminar un producto por ID
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del producto (ObjectId de MongoDB)
      responses:
        '200':
          description: Producto eliminado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Producto eliminado"
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized: Usuario no autenticado"
        '403':
          description: Rol insuficiente
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Forbidden: Rol insuficiente"
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Producto no encontrado"
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error al eliminar producto"